### ISSUE TITLE
IdentityIQ 8.3 - Unable to deploy identityiq

### ISSUE THREAD

**Issue by e8link** [JD10NN3/docker-sailpoint-identityiq#2]
Hi - Thanks for your excellent work!  I've been trying to get IIQ running on docker for a while.   So far I feel like I'm right at the finish line but I'm getting an error deploying identityiq.  

Binaries/base includes identityiq-8.3.zip.   
efixes is blank
patches is blank.

Updated .env for Tomcat 10.   

DB starts and I'm able to browse the database using the adminer web app.  
SP is running, I can login at ./iiq console - list users shows the admin account.  
I can access Tomcat manager, it shows identityiq as undeployed.
I can see the IIQ 8.3 files unzip during the build.

Error message:

docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.559 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/aarch64-linux-gnu/jni:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.708 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.719 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [279] milliseconds
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.747 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.747 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.23]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.754 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/opt/tomcat/conf/Catalina/localhost/manager.xml]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.766 WARNING [main] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase [/opt/tomcat/webapps/manager] inside the host appBase has been specified, and will be ignored
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.897 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/opt/tomcat/conf/Catalina/localhost/manager.xml] has finished in [143] ms
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.897 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/ROOT]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.910 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/ROOT] has finished in [13] ms
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:46.910 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/identityiq]
docker-sailpoint-identityiq-main-app-1      | 29-Aug-2022 18:58:50.373 SEVERE [main] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [/opt/tomcat/webapps/identityiq]
docker-sailpoint-identityiq-main-app-1      | 	java.lang.IllegalStateException: Error starting child
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1188)
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2023)
docker-sailpoint-identityiq-main-app-1      | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
docker-sailpoint-identityiq-main-app-1      | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
docker-sailpoint-identityiq-main-app-1      | 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
docker-sailpoint-identityiq-main-app-1      | 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)

Would appreciate any ideas on how to solve.

**Comment by e8link** [comment]
I decided to switch to Tomcat 9 and had no issues.   When I switch over to Tomcat 10 is when this error appears.  So for now I'll just Tomcat 9.
